# Generated by Django 3.1.2 on 2020-10-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('html_message', models.TextField(max_length=1500)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
