# Generated by Django 3.1.2 on 2020-10-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='html_message',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
